trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
  displayName: 'Install .NET SDK 8.x'

- script: dotnet build --configuration Release
  displayName: 'Build Solution'

- script: |
    dotnet test ind-tableau-alert-dashboard-risk-queue-unittest/ind-tableau-alert-dashboard-risk-queue-unittest.csproj \
      --collect "Code Coverage" \
      --configuration Release \
      --settings ./coverage.runsettings
  displayName: 'Run Tests with Code Coverage'