trigger:
- main  # Triggers on changes to the main branch

pool:
  vmImage: 'windows-latest'

steps:
# Step 1: Install .NET SDK 8
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # .NET 8 SDK
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Step 3: Restore NuGet Packages for the Project
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: |
      ind-tableau-alert-dashboard-risk-queue/ind-tableau-alert-dashboard-risk-queue.csproj
      ind-tableau-alert-dashboard-risk-queue-unittest/ind-tableau-alert-dashboard-risk-queue-unittest.csproj

# Step 4: Build the Projects
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      ind-tableau-alert-dashboard-risk-queue/ind-tableau-alert-dashboard-risk-queue.csproj
      ind-tableau-alert-dashboard-risk-queue-unittest/ind-tableau-alert-dashboard-risk-queue-unittest.csproj

# Step 5: Run Unit Tests and Collect Code Coverage
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
    publishTestResults: true
    projects: '**/*.Tests.csproj' # update with your test project directory

# Step 7: Publish Code Coverage Results
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
