trigger:
- none  # This triggers the pipeline for changes to the 'main' branch. Change if needed.

pool:
  vmImage: 'windows-latest'  # Using a Windows-based build agent

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Updated to .NET 8 SDK
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Step 2: Restore NuGet Packages for the C# Project and Test Project
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: |
      ind-tableau-alert-dashboard-risk-queue/ind-tableau-alert-dashboard-risk-queue.csproj
      ind-tableau-alert-dashboard-risk-queue-unittest/ind-tableau-alert-dashboard-risk-queue-unittest.csproj

- task: AdvancedSecurity-Codeql-Init@1
  inputs:
    enableAutomaticCodeQLInstall: true
    languages: 'csharp'
    querysuite: 'code-scanning'
    buildtype: 'Manual'


# Step 3: Build the Projects
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      ind-tableau-alert-dashboard-risk-queue/ind-tableau-alert-dashboard-risk-queue.csproj
      ind-tableau-alert-dashboard-risk-queue-unittest/ind-tableau-alert-dashboard-risk-queue-unittest.csproj


- task: AdvancedSecurity-Codeql-Analyze@1

- task: AdvancedSecurity-Publish@1