trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    #current_folder=$(basename $(pwd))
    current_folder="ind-tableau-alert-dashboard-risk-queue"
    project_path="$current_folder/$current_folder.csproj"
    dotnet restore $project_path
    dotnet build $project_path --configuration Release
    dotnet test $project_path --configuration Release --collect:"XPlat Code Coverage"
  displayName: 'Restore, Build, and Test'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/CodeCoverage'
    failIfCoverageEmpty: true

- script: |
    wget https://github.com/github/codeql-cli-binaries/releases/download/v2.7.2/codeql-linux64.zip
    unzip codeql-linux64.zip -d codeql
    ./codeql/codeql database create codeql-db --language=csharp --source-root=.
  displayName: 'Download and Initialize CodeQL'

- script: |
    ./codeql/codeql database analyze codeql-db --format=sarif-latest --output=codeql-results.sarif
  displayName: 'Analyze with CodeQL'
