trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
  displayName: 'Install .NET SDK 8.x'

- script: dotnet build ind-tableau-alert-dashboard-risk-queue/ind-tableau-alert-dashboard-risk-queue.sln --configuration Release
  displayName: 'Build Solution'

- script: dotnet test ind-tableau-alert-dashboard-risk-queue/ind-tableau-alert-dashboard-risk-queue.sln --collect "Code Coverage" --configuration Release --settings ./coverage.runsettings
  displayName: 'Run Tests with Code Coverage'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'VisualStudio'
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
  displayName: 'Publish Code Coverage Results'