trigger:
- main  # This triggers the pipeline for changes to the 'main' branch. Change if needed.

pool:
  vmImage: 'windows-latest'  # Using a Windows-based build agent

steps:
- task: AdvancedSecurity-Codeql-Init@1
  inputs:
    enableAutomaticCodeQLInstall: true
    querysuite: 'code-scanning'
    buildtype: 'None'
# Step 1: Install .NET SDK 8

# Step 5: Publish Code Coverage Results
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Coverlet'  # Use Coverlet for code coverage
    summaryFileLocation: '$(Build.SourcesDirectory)/TestResults/*.xml'  # Path to the code coverage summary
    reportDirectory: '$(Build.ArtifactStagingDirectory)/coverage-report'  # Output directory for coverage reports

- task: AdvancedSecurity-Codeql-Analyze@1

- task: AdvancedSecurity-Publish@1
