trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    current_folder='ind-tableau-alert-dashboard-risk-queue'
    project_path="$current_folder/$current_folder.csproj"
    dotnet restore $project_path
    dotnet build $project_path --configuration Release
  displayName: 'Restore and Build'

- script: |
    test_folder='ind-tableau-alert-dashboard-risk-queue-unittest'
    test_project_path="$test_folder/$test_folder.csproj"
    results_directory="$(System.DefaultWorkingDirectory)/TestResults"
    dotnet test $test_project_path --configuration Release --collect:"XPlat Code Coverage" --results-directory $results_directory
  displayName: 'Run Tests and Collect Coverage'

- script: |
    echo "Listing contents of $(System.DefaultWorkingDirectory):"
    ls -R $(System.DefaultWorkingDirectory)
  displayName: 'List Directory Contents'

- task: PublishCodeCoverageResults@2
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/TestResults/**/coverage.cobertura.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/CodeCoverage'
    failIfCoverageEmpty: true

# Step to download and initialize CodeQL binary
- script: |
    wget https://github.com/github/codeql-cli-binaries/releases/latest/download/codeql-linux64.zip -O codeql-linux64.zip
    unzip codeql-linux64.zip -d codeql
  displayName: 'Download and Initialize CodeQL Binary'

# Full clone of the CodeQL repository to ensure all dependencies are available
- script: |
    git clone --depth 1 https://github.com/github/codeql.git codeql-queries
  displayName: 'Clone Full CodeQL Repository'

# Step to install all dependencies for C# queries
- script: |
    cd codeql-queries
    ../codeql/codeql/codeql pack install
  displayName: 'Install CodeQL Pack Dependencies'

# Step to create the CodeQL database
- script: |
    ./codeql/codeql/codeql database create codeql-db --language=csharp --source-root=.
  displayName: 'Create CodeQL Database'

# Step to analyze the database with CodeQL using the C# queries
- script: |
    ./codeql/codeql/codeql database analyze codeql-db codeql-queries/csharp --format=sarif-latest --output=codeql-results.sarif
  displayName: 'Analyze with CodeQL'
