trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    current_folder='ind-tableau-alert-dashboard-risk-queue'
    project_path="$current_folder/$current_folder.csproj"
    dotnet restore $project_path
    dotnet build $project_path --configuration Release
  displayName: 'Restore and Build'

- script: |
    test_folder='ind-tableau-alert-dashboard-risk-queue-unittest'
    test_project_path="$test_folder/FunctionTests.csproj"
    results_directory="$(System.DefaultWorkingDirectory)/TestResults"
    dotnet test $test_project_path --configuration Release --collect:"XPlat Code Coverage" --results-directory $results_directory
  displayName: 'Run Tests and Collect Coverage'

- script: |
    echo "Listing contents of $(System.DefaultWorkingDirectory):"
    ls -R $(System.DefaultWorkingDirectory)
  displayName: 'List Directory Contents'

- task: PublishCodeCoverageResults@2
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/TestResults/**/coverage.cobertura.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/CodeCoverage'
    failIfCoverageEmpty: true

- script: |
    wget https://github.com/github/codeql-cli-binaries/releases/download/v2.7.2/codeql-linux64.zip
    unzip codeql-linux64.zip -d codeql
    ./codeql/codeql database create codeql-db --language=csharp --source-root=.
  displayName: 'Download and Initialize CodeQL'

- script: |
    ./codeql/codeql database analyze codeql-db --format=sarif-latest --output=codeql-results.sarif
  displayName: 'Analyze with CodeQL'
