# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- script: |
    echo "Installing CodeQL CLI..."
    wget https://github.com/github/codeql-cli-binaries/releases/download/v2.7.2/codeql-linux64.zip
    unzip codeql-linux64.zip -d codeql
    echo "##vso[task.setvariable variable=CODEQL_PATH]$(pwd)/codeql/codeql"
  displayName: 'Install CodeQL CLI'

- script: |
    export PATH=$PATH:$(CODEQL_PATH)
    codeql database create $(System.DefaultWorkingDirectory)/db --language=csharp
  displayName: 'Create CodeQL Database'


- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'